if(NOT DEFINED OBS_SOURCE_DIR)
  message(FATAL_ERROR "OBS_SOURCE_DIR is required")
endif()

function(require_text relative_path needle description)
  file(READ "${OBS_SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing contract: ${description} (${relative_path})")
  endif()
endfunction()

function(forbid_text relative_path needle description)
  file(READ "${OBS_SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden contract: ${description} (${relative_path})")
  endif()
endfunction()

require_text("libobs/obs-source.c" "mark_audio_graph_dirty_from_topology" "active-child topology invalidation")
require_text("plugins/obs-vst/obs-vst.cpp" "vst2_scan_result_passed" "VST2 passed-scan enforcement")
require_text("plugins/obs-vst/VST2ScanCache.cpp" "plugin_path_fingerprint_matches" "VST2 content-bound scan authorization")
require_text("plugins/obs-vst/obs-vst.cpp" "scanResults, false" "VST2 primary-cache-only enforcement")
require_text("plugins/obs-vst3/obs-vst3.cpp" "no passed scanner result" "VST3 passed-scan enforcement")
require_text("plugins/obs-vst3/obs-vst3.cpp" "hasCurrentFingerprint" "VST3 runtime fingerprint enforcement")
forbid_text("plugins/obs-vst3/obs-vst3.cpp" "vd->vst3_path = obs_data_get_string(settings, \"vst3_path\")" "VST3 saved-path fallback")
require_text("libobs/obs-audio-threaded.h" "obs_audio_threadpool_recommended_threads" "source-aware audio worker sizing")
require_text("frontend/components/ProgramAudioStrip.cpp" "setMeteringEnabled" "metering lifecycle control")
require_text("frontend/components/ProgramAudioStrip.cpp" "callbackTruePeak" "per-callback true-peak publication")
require_text("libobs/obs-audio-optimized.c" "obs_copy_overlapping_video_plane" "overlap-safe plane copy")
require_text("plugins/obs-vst3/obs-vst3.cpp" "vst3_output_float_count" "VST3 frame-count output allocation")
forbid_text("plugins/obs-vst3/obs-vst3.cpp" "da_resize(vd->output_data, out_size * vd->channels)" "byte-count DARRAY allocation")
require_text("shared/ipc-util/ipc-util/pipe-windows.c" "wait_for_overlapped_completion" "pending-I/O lifetime guard")
forbid_text("frontend/obs-main.cpp" "EnableForceRelocateImages = 1" "forced image relocation")
forbid_text("frontend/obs-main.cpp" "DisallowStrippedImages = 1" "stripped-image rejection")
require_text("frontend/widgets/OBSBasicStats.cpp" "cuDeviceGetLuid" "selected-adapter LUID matching")
require_text("frontend/widgets/OBSBasicStats.cpp" "LOAD_LIBRARY_SEARCH_SYSTEM32" "system-only NVIDIA library loading")
forbid_text("frontend/widgets/OBSBasicStats.cpp" "getHandle(0, &device)" "hard-coded NVML device zero")

message(STATUS "OBS fork source contracts passed")
