if(NOT DEFINED OBS_SOURCE_DIR)
  message(FATAL_ERROR "OBS_SOURCE_DIR is required")
endif()

function(require_text relative_path needle description)
  file(READ "${OBS_SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing contract: ${description} (${relative_path})")
  endif()
endfunction()

function(require_regex relative_path regex description)
  file(READ "${OBS_SOURCE_DIR}/${relative_path}" contents)
  string(REGEX MATCH "${regex}" match "${contents}")
  if(NOT match)
    message(FATAL_ERROR "Missing contract: ${description} (${relative_path})")
  endif()
endfunction()

function(forbid_text relative_path needle description)
  file(READ "${OBS_SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden contract: ${description} (${relative_path})")
  endif()
endfunction()

require_text("libobs/obs-source.c" "mark_audio_graph_dirty_from_topology" "active-child topology invalidation")
require_text("plugins/obs-vst/obs-vst.cpp" "vst2_scan_result_passed" "VST2 passed-scan enforcement")
require_text("plugins/obs-vst/VST2ScanCache.cpp" "plugin_path_fingerprint_matches" "VST2 content-bound scan authorization")
require_text("plugins/obs-vst/obs-vst.cpp" "scanResults, false" "VST2 primary-cache-only enforcement")
require_text("plugins/obs-vst3/obs-vst3.cpp" "no passed scanner result" "VST3 passed-scan enforcement")
require_text("plugins/obs-vst3/obs-vst3.cpp" "hasCurrentFingerprint" "VST3 runtime fingerprint enforcement")
forbid_text("plugins/obs-vst3/obs-vst3.cpp" "vd->vst3_path = obs_data_get_string(settings, \"vst3_path\")" "VST3 saved-path fallback")
require_text("libobs/obs-audio-threaded.h" "obs_audio_threadpool_recommended_threads" "source-aware audio worker sizing")
require_text("frontend/components/ProgramAudioStrip.cpp" "setMeteringEnabled" "metering lifecycle control")
require_text("frontend/components/ProgramAudioStrip.cpp" "callbackTruePeak" "per-callback true-peak publication")
require_text("libobs/obs-audio-optimized.c" "obs_copy_overlapping_video_plane" "overlap-safe plane copy")
require_text("plugins/obs-vst3/obs-vst3.cpp" "vst3_output_float_count" "VST3 frame-count output allocation")
forbid_text("plugins/obs-vst3/obs-vst3.cpp" "da_resize(vd->output_data, out_size * vd->channels)" "byte-count DARRAY allocation")
require_text("shared/ipc-util/ipc-util/pipe-windows.c" "wait_for_overlapped_completion" "pending-I/O lifetime guard")
forbid_text("frontend/obs-main.cpp" "EnableForceRelocateImages = 1" "forced image relocation")
forbid_text("frontend/obs-main.cpp" "DisallowStrippedImages = 1" "stripped-image rejection")
require_text("frontend/widgets/OBSBasicStats.cpp" "cuDeviceGetLuid" "selected-adapter LUID matching")
require_text("frontend/widgets/OBSBasicStats.cpp" "LOAD_LIBRARY_SEARCH_SYSTEM32" "system-only NVIDIA library loading")
forbid_text("frontend/widgets/OBSBasicStats.cpp" "getHandle(0, &device)" "hard-coded NVML device zero")

# Upstream backports (2026-09-24): keep them when merging a new upstream release.
forbid_text("libobs/obs-audio.c" "bool tasks_remaining = true;" "audio tasks executed while holding task_mutex (upstream 4315559a0)")
forbid_text("libobs/obs-video.c" "bool tasks_remaining = true;" "graphics tasks executed while holding task_mutex (upstream 4315559a0)")
require_text("frontend/widgets/AudioMixer.cpp" "QByteArray cachedName = control->getCachedName().toUtf8();" "owned Audio Mixer log name (upstream 36d134ee9)")
require_regex("frontend/widgets/OBSBasic_Profiles.cpp" "// Ensure defaults and updates are saved to disk[\r\n\t ]+activeConfiguration\\.SaveSafe\\(\"tmp\"\\);[\r\n\t ]+RefreshProfiles\\(\\);" "profile defaults saved after activation (upstream dfad5c86f)")
require_text("plugins/obs-outputs/mp4-output.c" "out->received_first_keyframe = false;" "per-recording b-frame split start correction (upstream f89ad4bee)")
require_regex("plugins/obs-outputs/mp4-output.c" "out->start_time = packet->dts_usec;[\r\n\t ]+out->chapter_base_usec = packet_pts_usec\\(packet\\);[\r\n\t ]+out->received_first_keyframe = true;" "first-keyframe b-frame start correction (upstream f89ad4bee)")
require_text("plugins/obs-outputs/mp4-output.c" "/ pkt->timebase_den) - out->chapter_base_usec;" "chapters placed from the keyframe presentation time")
forbid_text("plugins/obs-outputs/mp4-output.c" "/ pkt->timebase_den) - out->start_time;" "chapters shifted by the b-frame reorder delay")
require_text("plugins/obs-outputs/mp4-mux.c" "duration = track->fragment_samples.array[track->fragment_samples.num - 1].duration;" "last packet kept when finalising a Hybrid file (upstream 575c77f19)")
require_text("plugins/obs-outputs/mp4-mux.c" "const size_t end_offset = (final_flush && track != mux->chapter_track) ? 0 : 1;" "end-of-file Dummy chapter marker never emitted")
require_text("plugins/obs-outputs/mp4-output.c" "current_runtime >= out->max_time - 1000LL" "one-sided 1 ms split tolerance")
forbid_text("plugins/obs-outputs/mp4-output.c" "llabs(out->max_time - current_runtime) < 1000LL" "exact-match split window that never splits on non-dividing keyframe intervals")

message(STATUS "OBS fork source contracts passed")
